name: actopod

services:
  actopod-db:
    image: postgres:16-alpine
    container_name: actopod-db
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123}
      POSTGRES_DB: ${POSTGRES_DB:-actopod}
    volumes:
      - actopod_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-postgres}']
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 10s
    networks:
      - actopod_network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

volumes:
  actopod_db_data:
    driver: local

networks:
  actopod_network:
    driver: bridge
