export interface YouTubeExtractionOptions {
  preferredLanguage?: string;
  includeAutoGenerated?: boolean;
  maxRetries?: number;
  timeoutMs?: number;
}

export interface YouTubeTranscriptResult {
  videoId: string;
  videoTitle: string;
  transcript: string;
  language: string;
  captionType: 'manual' | 'auto' | 'none';
  characterCount: number;
  captionEventCount: number;
  extractedAt: Date;
  hasTranscript: boolean;
  error?: string;
  source?: 'subtitles' | 'no_captions' | 'error';
}

export interface YouTubeVideoDetails {
  title: string;
  description: string;
  subtitleCount: number;
  success: boolean;
}

export interface YouTubeCaption {
  id: string;
  language: string;
  trackKind: 'standard' | 'asr' | 'forced';
  name: string;
  isDefault: boolean;
  isAutoSynced: boolean;
  isCC: boolean;
}

export enum YouTubeExtractionStatus {
  SUCCESS = 'SUCCESS',
  PARTIAL_SUCCESS = 'PARTIAL_SUCCESS',
  NO_CAPTIONS = 'NO_CAPTIONS',
  FAILED = 'FAILED',
}

export interface YouTubeExtractionMetadata {
  status: YouTubeExtractionStatus;
  processingTimeMs: number;
  retryCount: number;
  errorMessage?: string;
}
